INSERT INTO computer (name, spec_id, status, computer_club_id, added_at, updated_at)
VALUES ('VIP-01', 1, 'VIP', 1, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 1, NOW(), NOW()),
       ('VIP-03', 1, 'SUPER_VIP', 1, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 1, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 1, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-03', 2, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-06', 3, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-08', 4, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-09', 5, 'DEFAULT', 1, NOW(), NOW()),
       ('PC-10', 5, 'DEFAULT', 1, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 2, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 2, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 2, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 2, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 2, NOW(), NOW()),
       ('VIP-06', 1, 'SUPER_VIP', 2, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-03', 2, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-08', 4, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-09', 5, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-10', 5, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-11', 2, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-12', 3, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-13', 4, 'DEFAULT', 2, NOW(), NOW()),
       ('PC-14', 5, 'DEFAULT', 2, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 3, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 3, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 3, NOW(), NOW()),
       ('VIP-04', 1, 'VIP', 3, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 3, NOW(), NOW()),
       ('VIP-06', 1, 'SUPER_VIP', 3, NOW(), NOW()),
       ('VIP-07', 1, 'SUPER_VIP', 3, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-03', 3, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-05', 4, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-08', 5, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-09', 5, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-10', 2, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-11', 3, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-12', 4, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-13', 5, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-14', 2, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-15', 3, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-16', 4, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-17', 5, 'DEFAULT', 3, NOW(), NOW()),
       ('PC-18', 2, 'DEFAULT', 3, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 4, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 4, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 4, NOW(), NOW()),
       ('VIP-04', 1, 'VIP', 4, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 4, NOW(), NOW()),
       ('VIP-06', 1, 'SUPER_VIP', 4, NOW(), NOW()),
       ('VIP-07', 1, 'SUPER_VIP', 4, NOW(), NOW()),
       ('VIP-08', 1, 'SUPER_VIP', 4, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-03', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-06', 3, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-08', 4, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-09', 4, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-10', 5, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-11', 5, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-12', 5, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-13', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-14', 3, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-15', 4, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-16', 5, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-17', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-18', 3, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-19', 4, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-20', 5, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-21', 2, 'DEFAULT', 4, NOW(), NOW()),
       ('PC-22', 3, 'DEFAULT', 4, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 5, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 5, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 5, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 5, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 5, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-02', 3, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-03', 4, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-04', 5, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-05', 2, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-06', 3, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-08', 5, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-09', 2, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-10', 3, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-11', 4, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-12', 5, 'DEFAULT', 5, NOW(), NOW()),
       ('PC-13', 2, 'DEFAULT', 5, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 6, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 6, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 6, NOW(), NOW()),
       ('VIP-04', 1, 'VIP', 6, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 6, NOW(), NOW()),
       ('VIP-06', 1, 'SUPER_VIP', 6, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-03', 3, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-05', 4, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-08', 5, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-09', 2, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-10', 3, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-11', 4, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-12', 5, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-13', 2, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-14', 3, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-15', 4, 'DEFAULT', 6, NOW(), NOW()),
       ('PC-16', 5, 'DEFAULT', 6, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 7, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 7, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 7, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 7, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 7, NOW(), NOW()),
       ('PC-01', 3, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-02', 4, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-03', 5, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-04', 2, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 7, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 7, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 8, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 8, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 8, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 8, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 8, NOW(), NOW()),
       ('PC-01', 1, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-03', 3, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-04', 4, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-05', 5, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-06', 2, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-07', 3, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-08', 4, 'DEFAULT', 8, NOW(), NOW()),
       ('PC-09', 5, 'DEFAULT', 8, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 9, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 9, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 9, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 9, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 9, NOW(), NOW()),
       ('PC-01', 4, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-02', 5, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-03', 1, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-04', 2, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-08', 2, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-09', 3, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-10', 4, 'DEFAULT', 9, NOW(), NOW()),
       ('PC-11', 5, 'DEFAULT', 9, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 10, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 10, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 10, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 10, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 10, NOW(), NOW()),
       ('VIP-06', 1, 'SUPER_VIP', 10, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-02', 3, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-03', 4, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-04', 5, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-05', 2, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-06', 3, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-08', 5, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-09', 2, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-10', 3, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-11', 4, 'DEFAULT', 10, NOW(), NOW()),
       ('PC-12', 5, 'DEFAULT', 10, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 11, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 11, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 11, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 11, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 11, NOW(), NOW()),
       ('PC-01', 1, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-03', 3, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-04', 4, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-05', 5, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-06', 2, 'DEFAULT', 11, NOW(), NOW()),
       ('PC-07', 3, 'DEFAULT', 11, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 12, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 12, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 12, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 12, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 12, NOW(), NOW()),
       ('PC-01', 3, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-02', 4, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-03', 5, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-04', 2, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 12, NOW(), NOW()),
       ('PC-08', 2, 'DEFAULT', 12, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 13, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 13, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 13, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 13, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 13, NOW(), NOW()),
       ('PC-01', 5, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-02', 1, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-03', 2, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-05', 4, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-06', 5, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-07', 2, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-08', 3, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-09', 4, 'DEFAULT', 13, NOW(), NOW()),
       ('PC-10', 5, 'DEFAULT', 13, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 14, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 14, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 14, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 14, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 14, NOW(), NOW()),
       ('PC-01', 2, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-02', 3, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-03', 4, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-04', 5, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-05', 2, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-06', 3, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-07', 4, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-08', 5, 'DEFAULT', 14, NOW(), NOW()),
       ('PC-09', 2, 'DEFAULT', 14, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 15, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 15, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 15, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 15, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 15, NOW(), NOW()),
       ('PC-01', 4, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-02', 5, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-03', 1, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-04', 2, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-08', 2, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-09', 3, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-10', 4, 'DEFAULT', 15, NOW(), NOW()),
       ('PC-11', 5, 'DEFAULT', 15, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 16, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 16, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 16, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 16, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 16, NOW(), NOW()),
       ('PC-01', 1, 'DEFAULT', 16, NOW(), NOW()),
       ('PC-02', 2, 'DEFAULT', 16, NOW(), NOW()),
       ('PC-03', 3, 'DEFAULT', 16, NOW(), NOW()),
       ('PC-04', 4, 'DEFAULT', 16, NOW(), NOW()),
       ('PC-05', 5, 'DEFAULT', 16, NOW(), NOW()),
       ('PC-06', 2, 'DEFAULT', 16, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 17, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 17, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 17, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 17, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 17, NOW(), NOW()),
       ('PC-01', 3, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-02', 4, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-03', 5, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-04', 2, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-05', 3, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-06', 4, 'DEFAULT', 17, NOW(), NOW()),
       ('PC-07', 5, 'DEFAULT', 17, NOW(), NOW()),


       ('VIP-01', 1, 'VIP', 18, NOW(), NOW()),
       ('VIP-02', 1, 'VIP', 18, NOW(), NOW()),
       ('VIP-03', 1, 'VIP', 18, NOW(), NOW()),
       ('VIP-04', 1, 'SUPER_VIP', 18, NOW(), NOW()),
       ('VIP-05', 1, 'SUPER_VIP', 18, NOW(), NOW()),
       ('PC-01', 5, 'DEFAULT', 18, NOW(), NOW()),
       ('PC-02', 1, 'DEFAULT', 18, NOW(), NOW()),
       ('PC-03', 2, 'DEFAULT', 18, NOW(), NOW()),
       ('PC-04', 3, 'DEFAULT', 18, NOW(), NOW()),
       ('PC-05', 4, 'DEFAULT', 18, NOW(), NOW());


